### ISSUE TITLE
please do 1.11.2

### ISSUE THREAD

**Issue by ghost** [mezz/NoPotionShift#1]
plz.....

**Comment by mezz** [comment]
Sure

**Comment by mezz** [comment]
Uploaded to Curse, should be there in a few minutes.
https://minecraft.curseforge.com/projects/no-potion-shift/files

**Comment by ghost** [comment]
omg, you really did it! Thank you so much my friend!

**Comment by bochen415** [comment]
Could we get a build going for 1.12.2 too?

**Comment by mezz** [comment]
Sure, here: https://minecraft.curseforge.com/projects/no-potion-shift/files/2498342
