### ISSUE TITLE
1.16.4 version

### ISSUE THREAD

**Issue by Trnrr** [mezz/NoPotionShift#5]
Hello if you get some free time it would be amazing if you could update it to 1.16.4.

It crashes forge 1.16.4 saying it's missing license information. "net.minecraftforge.fml.ModLoadingException: Missing License Information in file Mod File: C:\_gdl\instances\Enhanced Vanilla Tech\mods\nopotionshift_1.16.1-1.5.0.jar"

**Comment by Gliese-832-c** [comment]
A fellow GDLauncher user! :D

I can confirm, I am getting that issue too. It needs to be fixed, as the potion shifting is annoying and there is no other mod in 1.16.4 does something like this.

**Comment by mezz** [comment]
Thanks for the request!
I have updated the mod for 1.16.4 here, it should be available soon:
https://www.curseforge.com/minecraft/mc-mods/no-potion-shift/files/3179976
